version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: mongodb-newton
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: newton_ai
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    networks:
      - newton-network

  # Optional: MongoDB Express for web-based admin
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express-newton
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: webpass123
    depends_on:
      - mongodb
    networks:
      - newton-network

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local

networks:
  newton-network:
    driver: bridge
