[project]
name = "newton-llm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aws-lambda-powertools>=3.19.0",
    "beautifulsoup4>=4.13.5",
    "selenium>=4.35.0",
]
